// Must be the exact same Firebase project as the host app
// (../../host/src/firebase/config.ts) -- this is what makes an event code
// generated by a host phone resolvable from a verifier phone. Safe to commit;
// see the host app's config.ts for why.
export const firebaseConfig = {
  apiKey: 'REPLACE_ME',
  authDomain: 'REPLACE_ME.firebaseapp.com',
  projectId: 'REPLACE_ME',
  storageBucket: 'REPLACE_ME.appspot.com',
  messagingSenderId: 'REPLACE_ME',
  appId: 'REPLACE_ME',
};
