// Must be the exact same Firebase project as the host app
// (../../host/src/firebase/config.ts) -- this is what makes an event code
// generated by a host phone resolvable from a verifier phone. Safe to commit;
// see the host app's config.ts for why.
export const firebaseConfig = {
  apiKey: 'AIzaSyBjSNZbQrDMCSfTo0DA30cdIAM2YhuW2rQ',
  authDomain: 'thh-tickets.firebaseapp.com',
  projectId: 'thh-tickets',
  storageBucket: 'thh-tickets.firebasestorage.app',
  messagingSenderId: '346806544306',
  appId: '1:346806544306:web:82d8712ad7fba3e655e6ab',
};
